runtime: nodejs18
instance_class: F2
env: standard

handlers:
  # Serve static files from the build directory
  - url: /static
    static_dir: build/static

  # Serve the favicon
  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico

  # Serve the manifest
  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json

  # Serve the service worker
  - url: /service-worker.js
    static_files: build/service-worker.js
    upload: build/service-worker.js

  # Catch-all handler for React routing (includes root `/`)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
